default-steps: &default-steps
  steps:
    - checkout
    - run:
        name: Build
        command: |
          ./make-znapzend.py
    - store_artifacts:
        path: worksavedir

version: 2
jobs:
  build-current:
    working_directory: /tmp/build
    docker:
      - image: mumblepins/circleci-dev:ubuntu-debuild
    <<: *default-steps

  build-lts:
      working_directory: /tmp/build
      docker:
        - image: mumblepins/circleci-dev:ubuntu-LTS-debuild
      <<: *default-steps


workflows:
  version: 2
  build-all:
    jobs:
      - build-lts
      - build-current